language: java

sudo: false
# manage the caches here https://travis-ci.org/hawkular/hawkular.github.io/caches
cache:
  directories:
    - $HOME/.m2/repository

jdk:
- oraclejdk8

notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change
    on_failure: change

env:
  global:
    # token used for pushing the built website back to github
    secure: "ffozNmbm6jDaqpfw70q6Es2JsXCyCnsLsGq3ER49tTPFGSnw1o1CEBKSjHXBYFOCfWXReFAlwGJzVVURRAlYs5yNL4//a/KosM1vhiJx269MwjuVK9v9zElQyeC7arvjQb3AT0GpEzhSQYQ0Rlg2+fb1MjHGXdUnIO8OiNH1jc8="

before_install:
  # download all the swagger adoc files
  - bash -x ./.travis.swagger.sh

script:
  - cat ./src/main/jbake/jbake.properties
  # bake the pages
  - mvn install -B

after_success:
  # push to master
  - test "${TRAVIS_BRANCH}" = "pages" && test "${TRAVIS_PULL_REQUEST}" = "false" && mvn -s .travis.settings.xml site
  # deploy the PR
  - test "${TRAVIS_BRANCH}" = "pages" && [[ "$TRAVIS_PULL_REQUEST" != "false" ]] && bash -x ./pr-auto-deploy/client.sh "${TRAVIS_PULL_REQUEST}" "${DEPLOY_PR_HOST}"
