language: java
jdk:
- oraclejdk8

notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change

env:
  global:
    secure: "Vxy94O4cbUkWnpt9PPgKpvgRj16ULKXl/lplPTMjSdwVK6HEE/t7xsQcRFcSHm/4/oyXrNS2QEWBwxbH7lX4qxw5ryHKzKeHuPE6Q7zQPWDYaFqQm0ufUJpy1NmBk8RTAgZE1Ot7xZeH6bZCzUF0tk2MNrstRaqljzop+ZaLXhE="
install:
  - mvn -s settings.xml install
