language: java

sudo: false
# manage the caches here https://travis-ci.org/hawkular/hawkular.github.io/caches
cache:
  directories:
    - $HOME/.m2/repository

jdk:
- oraclejdk8

notifications:
  irc:
    channels:
    - chat.freenode.net#hawkular
    on_success: change
    on_failure: change

env:
  global:
    # token used for pushing the built website back to github (hawkular-website-bot)
    secure: "GBXOczQJ6ouFweXASfR+Nnlz2//0cyt7qexj9EkjfxWd1qajN3WaD1aqkEjJwCefiQZh4iHJR7iMVoBHKr4b//7qsuVQ82FjwrVBaJsd2J9AbSnqZLhNV7cQL9gd67UDt9bx33QpJaD4UvjQlKG95dWnoNn1pIsM6J4xdc3XMCA="
before_install:
  # download all the swagger adoc files
  - bash -x ./.travis.swagger.sh

script:
  # bake the pages
  - mvn install -B

after_success:
  # push to master
  - test "${TRAVIS_BRANCH}" = "pages" && test "${TRAVIS_PULL_REQUEST}" = "false" && mvn -s .travis.settings.xml site
  # deploy the PR
  - test "${TRAVIS_BRANCH}" = "pages" && [[ "$TRAVIS_PULL_REQUEST" != "false" ]] && bash -x ./pr-auto-deploy/client.sh "${TRAVIS_PULL_REQUEST}" "${DEPLOY_PR_HOST}"
